import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { NavMenu } from "./components/home/nav-menu";
import { Avatar, AvatarFallback, AvatarImage } from "./components/ui/avatar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <div className="flex h-screen flex-col">
          <header className="flex h-16 shrink-0 items-center justify-between  border-b px-4 dark:bg-gray-700 md:px-6">
            <div className="flex gap-2">
              <Avatar>
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>CC</AvatarFallback>
              </Avatar>
              <Link className="flex items-center gap-2" href="/">
                <h1 className="text-lg font-semibold">Workout Tracker</h1>
              </Link>
            </div>
            <NavMenu />
          </header>
          <main className="flex-1 bg-gray-100 p-4 dark:bg-gray-700 md:p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
