import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { NavMenu } from "./tracker/home/nav-menu";
import { Avatar, AvatarFallback, AvatarImage } from "./components/ui/avatar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <div className="flex h-screen flex-col">{children}</div>
      </body>
    </html>
  );
}
