import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen flex-col">
          <header className="flex h-16 items-center border-b px-4 md:px-6">
            <Link className="flex items-center gap-2" href="/">
              <MountainIcon className="h-6 w-6" />
              <span className="text-lg font-semibold">Workout Tracker</span>
            </Link>
          </header>
          <main className="flex-1 bg-gray-100 p-4 dark:bg-gray-900 md:p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

function MountainIcon(props: React.HTMLAttributes<HTMLOrSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
